### ISSUE TITLE
Scoreboard textual issue after 0 seconds.

### ISSUE THREAD

**Issue by J-Wass** [SaltieRL/WebReplayViewer#46]
![scoreboard](https://user-images.githubusercontent.com/2034868/60388645-7c599500-9a69-11e9-9c12-b81e450a2d63.png)

**Comment by Abbondanzo** [comment]
Can I get a link to that replay?

**Comment by J-Wass** [comment]
This code block doesn't handle this endcase correctly: https://github.com/SaltieRL/WebReplayViewer/blob/master/src/viewer/components/ScoreBoard.tsx#L52

**Comment by J-Wass** [comment]
https://calculated.gg/replays/AFDEB05E11E993DE4A0C42B3F0EBD415
