### ISSUE TITLE
Do not unload viewer if user switches tab

### ISSUE THREAD

**Issue by dtracers** [SaltieRL/WebReplayViewer#53]

**Comment by Abbondanzo** [comment]
What would we want to do? We can store game state in terms of the last frame they visited

**Comment by dtracers** [comment]
Yeah I think that is valid.

What is most important is not unloading the assets and replay data itself.

**Comment by Abbondanzo** [comment]
The assets are cached to the user's session but the replay data isn't cached by the library. I can add data caching

**Comment by Abbondanzo** [comment]
#57 caches loaded data
