### ISSUE TITLE
this.chassisMaterial.normalMap is undefined

### ISSUE THREAD

**Issue by drake7707** [SaltieRL/WebReplayViewer#94]
An error occurred while loading: this.chassisMaterial.normalMap is undefined

Replay: https://calculated.gg/replays/43103C9A11EAD6810A94A29CE9134521

**Comment by Abbondanzo** [comment]
@Longi94 
The chassis material is getting fed an undefined asset image, so `htmlImageToTexture` returns undefined [here](https://github.com/Longi94/rl-loadout-lib/blob/07121fb5fcc1c626e48cad2bb22de93b5f70660d/src/3d/body/slime-model.ts#L39)

**Comment by Longi94** [comment]
I'll look into it when I can

**Comment by Longi94** [comment]
Fixed, thanks!
