### ISSUE TITLE
Crashes on Chrome

### ISSUE THREAD

**Issue by binury** [SaltieRL/WebReplayViewer#96]
![image](https://user-images.githubusercontent.com/1146921/95240090-84a69100-07d1-11eb-981d-95db6ee0574e.png)

Using a custom-limit flag with the browser binary looks to be a workaround.
`max-active-webgl-contexts` like
`/Applications/Google\ Chrome.app/Contents/MacOS/Google\ Chrome --max-active-webgl-contexts=500`
> Chrome’s WebGL context limit is 16

( I used 87.0.4278.0 )

**Comment by binury** [comment]
I noticed this repo is using semver ranges instead of static dependencies which seems problematic— and might give rise to these kinds of issues in the future, too

**Comment by Abbondanzo** [comment]
This seems like a likely culprit, although I couldn't easily insert breakpoints to confirm since neither FF nor Chrome support that on source maps :/
https://github.com/SaltieRL/WebReplayViewer/blob/2d62bcdc6ffb217a0d0682ebe082676018ec83fd/src/managers/GameManager.ts#L39

**Comment by Abbondanzo** [comment]
Should be fixed by https://github.com/SaltieRL/DistributedReplays/pull/473

**Comment by Abbondanzo** [comment]
^ has been merged
